name: jFrog Docker Integration Test
on: [push]

env:
  RUN_NUMBER: ${{ github.run_number }}
permissions:
  id-token: write
  contents: read 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: JFrog Setup
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4.2.2
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: githubpro
          oidc-audience: test
      - name: JFrog Setup
        run: jf rt ping







          
